/* -------------------------------------------------------------------------- */
/*  Tarjetas de la parrilla del hub clínico.                                   */
/*                                                                            */
/*  Vive en su propio módulo de DATOS —como `Creditos/orbitModules.ts`— para   */
/*  que se pueda contar y comprobar sin arrastrar la pantalla entera: al       */
/*  importarla, `react-redux` y gluestack llegan como ESM y jest no los        */
/*  transforma. La constelación de créditos cuenta desde aquí.                 */
/* -------------------------------------------------------------------------- */

import type { RootStackParamList } from '@/Navigators';
import {
  AudioWaveform,
  BrainCircuit,
  Droplets,
  Ear,
  Mic,
  MoonStar,
  Puzzle,
  Speech,
  TrainFront,
} from 'lucide-react-native';

import type { ModuleCardData } from './ModuleCardItem';

type ModuleCard = ModuleCardData & { id: keyof RootStackParamList };

export const MODULES: ModuleCard[] = [
  {
    id: 'Audiometry',
    title: 'Audiometría Infantil',
    description: 'Audiometría tonal liminar por juego (play audiometry).',
    duration: '8–10 min',
    durationMinutes: 9,
    ages: '2–6 años',
    icon: Ear,
    category: 'hearing',
    tag: 'AUDICIÓN',
    color: '#0284C7',
    soft: '#E0F2FE',
    isCalibrated: true,
  },
  {
    id: 'AudiometryConditioned',
    title: 'Audiometría Condicionada',
    subtitle: '(El Tren del Sonido)',
    description: 'Audiometría por condicionamiento con refuerzo visual animado.',
    duration: '8–10 min',
    durationMinutes: 9,
    ages: '2–6 años',
    icon: TrainFront,
    category: 'hearing',
    tag: 'AUDICIÓN',
    color: '#0D9488',
    soft: '#CCFBF1',
    isCalibrated: true,
  },
  {
    id: 'VerbalAudiometry',
    title: 'Audiometría Verbal',
    description: 'Reconocimiento de palabras por tarjetas en campo libre.',
    duration: '8–10 min',
    durationMinutes: 8,
    ages: '2 años – adulto',
    icon: Speech,
    category: 'hearing',
    tag: 'AUDICIÓN',
    color: '#2563EB',
    soft: '#DBEAFE',
    isCalibrated: true,
  },
  {
    id: 'VoiceAnalysis',
    title: 'Análisis Acústico de Voz',
    description: 'Vocal sostenida /a/ · Frecuencia fundamental y formantes.',
    duration: '3–5 min',
    durationMinutes: 4,
    ages: 'Todas las edades',
    icon: Mic,
    category: 'voice',
    tag: 'VOZ',
    color: '#7C3AED',
    soft: '#F3E8FF',
    badgeParam: 'F0, jitter, shimmer',
  },
  {
    id: 'Articulation',
    title: 'Articulación · T.A.R.',
    description: 'Test de Articulación a la Repetición · registro SODA.',
    duration: '8–12 min',
    durationMinutes: 10,
    ages: '3–7 años',
    icon: Speech,
    category: 'neuro',
    tag: 'NEURODESARROLLO',
    color: '#EA580C',
    soft: '#FFEDD5',
    badgeParam: 'SODA Fonética',
  },
  {
    id: 'ExecutiveFunctions',
    title: 'Funciones Ejecutivas',
    description: 'Cinco mini-juegos: atención, inhibición, flexibilidad, memoria y planificación.',
    duration: '8–10 min',
    durationMinutes: 9,
    ages: '3–12 años',
    icon: BrainCircuit,
    category: 'neuro',
    tag: 'NEURODESARROLLO',
    color: '#059669',
    soft: '#D1FAE5',
    isCalibrated: true,
  },
  {
    id: 'ProsodyAnalysis',
    title: 'Análisis Prosódico',
    description: 'Habla conectada · ritmo, entonación, pausas y modulación.',
    duration: '4–6 min',
    durationMinutes: 5,
    ages: '3–12 años',
    icon: AudioWaveform,
    category: 'voice',
    tag: 'VOZ',
    color: '#C026D3',
    soft: '#FAE8FF',
    badgeParam: 'Prosodia DSP',
  },
  {
    id: 'Mchat',
    title: 'Cuestionario Autismo',
    subtitle: '(M-CHAT-R/F)',
    description: 'Cribado conductual de señales tempranas de TEA.',
    duration: '5–10 min',
    durationMinutes: 7,
    ages: '16–30 meses',
    icon: Puzzle,
    category: 'neuro',
    tag: 'NEURODESARROLLO',
    color: '#DB2777',
    soft: '#FCE7F3',
    badgeParam: '20 Ítems M-CHAT',
  },
  {
    id: 'SahsScreening',
    title: 'Cribado SAHS Infantil',
    description: 'Cuestionario PSQ de Chervin y exploración física (Brodsky, IMC).',
    duration: '5–8 min',
    durationMinutes: 6,
    ages: '2–12 años',
    icon: MoonStar,
    category: 'sleep',
    tag: 'SUEÑO',
    color: '#4F46E5',
    soft: '#E0E7FF',
    badgeParam: 'Brodsky + PSQ',
  },
  {
    id: 'DysphagiaTest',
    title: 'Exploración de Disfagia',
    description: 'MECV-V volumen-viscosidad con pulsioximetría integrada · sin CAP ni sonómetro.',
    duration: '10–15 min',
    durationMinutes: 12,
    ages: 'Todas las edades',
    icon: Droplets,
    category: 'dysphagia',
    tag: 'DEGLUCIÓN',
    color: '#DC2626',
    soft: '#FEE2E2',
    badgeParam: 'SpO₂ · desaturación',
  },
  {
    id: 'AshaScreening',
    title: 'Hitos del Lenguaje ASHA',
    subtitle: '(Percentil 75)',
    description: 'Cribado normativo (0–5 años) de dominios comunicativos con motor CDSS y alertas.',
    duration: '5–8 min',
    durationMinutes: 6,
    ages: '0–5 años',
    icon: Puzzle,
    category: 'neuro',
    tag: 'NEURODESARROLLO',
    color: '#0D9488',
    soft: '#CCFBF1',
    badgeParam: 'CDSS Percentil 75',
  },
];
